[package]
name = "dcs-radio-station"
version = "1.0.0-alpha.7"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-std = "1.0"
clap = "2.32"
env_logger = "0.7"
futures = "0.3"
log = "0.4"
ogg = "0.7"
srs = { path = "../srs" }
tokio = { version = "0.2", features = ["macros", "time", "net"] }
